Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using Salon_and_Spa.Models;

namespace Salon_and_Spa.Controllers
{
    public class OwnerController : Controller
    {
        // GET: Owner
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Owner model)
        {
            using (var conetxt = new SalonEntities())
            {
                bool isvalid = conetxt.Salon_Owner.Any(x => x.EmailId == model.EmailId && x.Password == model.Password);
                if (isvalid)
                {
                    FormsAuthentication.SetAuthCookie(model.EmailId, false);
                    return RedirectToAction("Index", "Booking");
                }
                ModelState.AddModelError("", "Invalid UserName or Password");
                return View();
            }
        }

        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignUp(Owner model)
        {
            if (ModelState.IsValid)
            {
                using (var context = new SalonEntities())
                {
                    Salon_Owner salon_Owner = new Salon_Owner()
                    {
                        Name_Of_The_Salon = model.Name_Of_The_Salon,
                        EmailId = model.EmailId,
                        Location = model.Location,
                        Password = model.Password,
                        Phone_Number = model.Phone_Number,
                        Price = model.Price
                    };
                    context.Salon_Owner.Add(salon_Owner);
                    context.SaveChanges();
                }
                return RedirectToAction("login");
            }
            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("index", "home");
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Salon_and_Spa.Models;

namespace Salon_and_Spa.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User model)
        {
            using (var conetxt = new SalonEntities())
            {
                
                bool isvalid = conetxt.General_User.Any(x => x.UserName == model.UserName && x.Password == model.Password);
                if (isvalid)
                {
                    FormsAuthentication.SetAuthCookie(model.UserName, false);
                    return RedirectToAction("Index", "Salon_Owner");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid UserName or Password");
                }
                return View();
            }
                
        }


        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignUp(User model)
        {
            if (ModelState.IsValid)
            {
                using (var context = new SalonEntities())
                {
                    General_User general_User = new General_User()
                    {
                        UserName = model.UserName,
                        Password = model.Password,

                    };
                    context.General_User.Add(general_User);
                    context.SaveChanges();
                }
                return RedirectToAction("login");
            }
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">


                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a>Dear - @User.Identity.Name</a></li>
                        <li>@Html.ActionLink("Logout", "Logout", "owner");</li>
                    }
                    else
                    {
                        <h1>
                            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("User Login", "Login", "User", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Corporate User Login", "Login", "Owner", new { area = "" }, new { @class = "navbar-brand" })
                         </h1>

                    }

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Salon and Spa Booking </p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>