Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Salon_and_Spa;
using Salon_and_Spa.Models;

namespace Salon_and_Spa.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private SalonEntities db = new SalonEntities();

        // GET: Booking
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.General_User).Include(b => b.Salon_Owner);
            return View(books.ToList());
        }

        public ActionResult UpcomingBooking()
        {
            var books = db.Books.Include(b => b.General_User).Include(b => b.Salon_Owner);
            return View(books.ToList());
        }
        // GET: Booking/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Booking/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.General_User, "UserId", "UserName");
            ViewBag.CorporateId = new SelectList(db.Salon_Owner, "CorporateId", "Name_Of_The_Salon");
            return View();
        }

        // POST: Booking/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,CorporateId,Date,Time")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.General_User, "UserId", "UserName", book.UserId);
            ViewBag.CorporateId = new SelectList(db.Salon_Owner, "CorporateId", "Name_Of_The_Salon", book.CorporateId);
            return View(book);
        }

        // GET: Booking/Edit/5
        public ActionResult Edit(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            TempData["UserId"] = book.UserId;
            TempData["CorporateId"] = book.CorporateId;
            return View(book);
        }

        // POST: Booking/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,CorporateId,Date,Time")] Book book)
        {
            SalonEntities salonEntities = new SalonEntities();
            foreach(var item in salonEntities.Books)
            {
                if(book.Id== item.Id)
                {
                    book.UserId = item.UserId;
                    book.CorporateId = item.CorporateId;
                }
            }
            
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index","booking");
            }
            ViewBag.UserId = new SelectList(db.General_User, "UserId", "UserName", book.UserId);
            ViewBag.CorporateId = new SelectList(db.Salon_Owner, "CorporateId", "Name_Of_The_Salon", book.CorporateId);
            return View(book);
        }

        // GET: Booking/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Booking/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult History()
        {
            SalonEntities salonEntities = new SalonEntities();

            return View(salonEntities.Books.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/Salon_OwnerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Salon_and_Spa.Models;

using Salon_and_Spa.Models;
namespace Salon_and_Spa.Controllers
{
    [Authorize]
    public class Salon_OwnerController : Controller
    {
        private SalonEntities db = new SalonEntities();
        private readonly object userid;

        // GET: Salon_Owner
        public ActionResult Index()
        {
            
            TempData.Keep("UserId");
            return View(db.Salon_Owner.ToList());
        }

        // GET: Salon_Owner/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salon_Owner salon_Owner = db.Salon_Owner.Find(id);
            if (salon_Owner == null)
            {
                return HttpNotFound();
            }
            return View(salon_Owner);
        }

   /*     // GET: Salon_Owner/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Salon_Owner/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CorporateId,Name_Of_The_Salon,EmailId,Location,Password,Phone_Number,Price")] Salon_Owner salon_Owner)
        {
            if (ModelState.IsValid)
            {
                db.Salon_Owner.Add(salon_Owner);
                db.SaveChanges();
                return RedirectToAction("index");
            }

            return View(salon_Owner);
        }
        */
        // GET: Salon_Owner/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salon_Owner salon_Owner = db.Salon_Owner.Find(id);
            if (salon_Owner == null)
            {
                return HttpNotFound();
            }
            return View(salon_Owner);
        }

        // POST: Salon_Owner/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CorporateId,Name_Of_The_Salon,EmailId,Location,Password,Phone_Number,Price")] Salon_Owner salon_Owner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(salon_Owner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(salon_Owner);
        }

        // GET: Salon_Owner/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salon_Owner salon_Owner = db.Salon_Owner.Find(id);
            if (salon_Owner == null)
            {
                return HttpNotFound();
            }
            return View(salon_Owner);
        }

        // POST: Salon_Owner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Salon_Owner salon_Owner = db.Salon_Owner.Find(id);
            db.Salon_Owner.Remove(salon_Owner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public  ActionResult  Booking(int id)
        {
            General_User genral_user = new General_User(); 
            TempData["CorporateId"] = id;
            return RedirectToAction("Create", "Books");
        }
    }
}

Views/Salon_Owner/Create.cshtml
@model Salon_and_Spa.Salon_Owner

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Salon_Owner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name_Of_The_Salon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_Of_The_Salon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_Of_The_Salon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone_Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone_Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Salon_Owner/Delete.cshtml
@model Salon_and_Spa.Salon_Owner

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Salon_Owner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_Of_The_Salon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_Of_The_Salon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Salon_Owner/Details.cshtml
@model Salon_and_Spa.Salon_Owner

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Salon_Owner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_Of_The_Salon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_Of_The_Salon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.Phone_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Salon_Owner/Edit.cshtml
@model Salon_and_Spa.Salon_Owner

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Salon_Owner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CorporateId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name_Of_The_Salon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_Of_The_Salon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_Of_The_Salon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone_Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone_Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Salon_Owner/Index.cshtml
@model IEnumerable<Salon_and_Spa.Salon_Owner>

@{
    ViewBag.Title = "Index";
}

<h2>Index |</h2>
@Html.ActionLink("History","History","Books") |
@Html.ActionLink("Upcoming Booking", "UpcomingBooking","Books")


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name_Of_The_Salon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone_Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name_Of_The_Salon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone_Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
           
                
                @Html.ActionLink("Book", "Booking", new { id = item.CorporateId }) |
                @Html.ActionLink("Details", "Details", new { id=item.CorporateId }) |
           
        </td>
    </tr>
}

</table>